# Development and testing for private prisons visualization

## Script test

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from src.visualization.state_of_our_prisons import plotly_private_prisons

In [4]:
df = plotly_private_prisons.test_data()
df

       prison_name provider postal_code   latitude  longitude
0        Altcourse   Sodexo      L9 7LH  53.460927  -2.936031
1         Ashfield    Serco    BS16 9QJ  51.482420  -2.438869
2      Bronzefield   Sodexo    TW15 3JZ  51.432921  -0.482850
3        Doncaster    Serco     DN5 8UX  53.525178  -1.145003
4         Dovegate    Serco    ST14 8XR  52.872046  -1.783109
5       Five Wells      G4S     NN8 2NH  52.297422  -0.697031
6      Forest Bank   Sodexo     M27 8FB  53.514251  -2.302093
7        Fosse Way    Serco    LE18 4TN  52.582480  -1.143503
8   Northumberland   Sodexo    NE65 9XG  55.296086  -1.635300
9          Oakwood      G4S    WV10 7QD  52.647955  -2.113013
10            Parc      G4S    CF35 6AP  51.530946  -3.563142
11    Peterborough   Sodexo     PE3 7PD  52.586514  -0.259961
12        Rye Hill      G4S    CV23 8SZ  52.327520  -1.242801
13       Thameside    Serco    SE28 0FJ  51.493450   0.087506

In [5]:
traces = plotly_private_prisons.generate_traces(df)
traces

[Scattermap({
     'hovertemplate': '%{text}',
     'lat': array([52.297422, 52.647955, 51.530946, 52.32752 ]),
     'lon': array([-0.697031, -2.113013, -3.563142, -1.242801]),
     'marker': {'color': '#ef3e42', 'size': 9},
     'mode': 'markers',
     'name': 'G4S',
     'text': array(['Five Wells', 'Oakwood', 'Parc', 'Rye Hill'], dtype=object)
 }),
 Scattermap({
     'hovertemplate': '%{text}',
     'lat': array([51.48242 , 53.525178, 52.872046, 52.58248 , 51.49345 ]),
     'lon': array([-2.438869, -1.145003, -1.783109, -1.143503,  0.087506]),
     'marker': {'color': '#46555f', 'size': 9},
     'mode': 'markers',
     'name': 'Serco',
     'text': array(['Ashfield', 'Doncaster', 'Dovegate', 'Fosse Way', 'Thameside'],
                   dtype=object)
 }),
 Scattermap({
     'hovertemplate': '%{text}',
     'lat': array([53.460927, 51.432921, 53.514251, 55.296086, 52.586514]),
     'lon': array([-2.936031, -0.48285 , -2.302093, -1.6353  , -0.259961]),
     'marker': {'color': '#283897', 'size': 9},
     'mode': 'markers',
     'name': 'Sodexo',
     'text': array(['Altcourse', 'Bronzefield', 'Forest Bank', 'Northumberland',
                    'Peterborough'], dtype=object)
 })]

In [ ]:
fig = plotly_private_prisons.create_chart(df)
fig.show(config={'displayModeBar': False})

In [8]:
fig.write_html("reports/figures/state_of_our_prisons/private_prisons.html", full_html=True, include_plotlyjs="cdn", config = {'displayModeBar': False})

In [ ]:
fig.to_html(full_html=True, include_plotlyjs="cdn", config = {'displayModeBar': False})

## Minimal reproducable example: Not displaying on Chart Studio

In [1]:
import chart_studio.plotly as py
import pandas as pd
import plotly.graph_objs as go
import plotly.io as pio

In [2]:
df = pd.DataFrame({"location_name": ["London", "Birmingham", "Manchester", "Cardiff"], "lat": [51.5074, 52.4862, 53.4808, 51.4816], "lon": [-0.1278, -1.8904, -2.2426, -3.1791]})
df

  location_name      lat     lon
0        London  51.5074 -0.1278
1    Birmingham  52.4862 -1.8904
2    Manchester  53.4808 -2.2426
3       Cardiff  51.4816 -3.1791

In [8]:
def generate_traces(df: pd.DataFrame) -> list:
    """Generate traces for the chart."""
    colors = {
        "London": "Blue",
        "Birmingham": "Red",
        "Manchester": "Green",
        "Cardiff": "Yellow",
    }

    traces = [
        go.Scattermap(
            lat = df_location['lat'].tolist(),
            lon = df_location['lon'].tolist(),
            mode = 'markers',
            marker=go.scattermap.Marker(
                size=9,
                color= colors[location],
            ),
            text = df_location['location_name'].tolist(),
            hovertemplate="%{text}",
            name=str(location),
        )
        for location, df_location in df.groupby('location_name')
    ]

    return traces

In [9]:
traces = generate_traces(df)
traces

[Scattermap({
     'hovertemplate': '%{text}',
     'lat': [52.4862],
     'lon': [-1.8904],
     'marker': {'color': 'Red', 'size': 9},
     'mode': 'markers',
     'name': 'Birmingham',
     'text': [Birmingham]
 }),
 Scattermap({
     'hovertemplate': '%{text}',
     'lat': [51.4816],
     'lon': [-3.1791],
     'marker': {'color': 'Yellow', 'size': 9},
     'mode': 'markers',
     'name': 'Cardiff',
     'text': [Cardiff]
 }),
 Scattermap({
     'hovertemplate': '%{text}',
     'lat': [51.5074],
     'lon': [-0.1278],
     'marker': {'color': 'Blue', 'size': 9},
     'mode': 'markers',
     'name': 'London',
     'text': [London]
 }),
 Scattermap({
     'hovertemplate': '%{text}',
     'lat': [53.4808],
     'lon': [-2.2426],
     'marker': {'color': 'Green', 'size': 9},
     'mode': 'markers',
     'name': 'Manchester',
     'text': [Manchester]
 })]

In [15]:
def create_chart(df: pd.DataFrame) -> go.Figure:

    fig = go.Figure()
    traces = generate_traces(df)
    fig.add_traces(traces)

    fig.update_layout(
        margin=dict(l=0, r=0, t=0, b=0),
        map=dict(
            bearing=0,
            center=dict(
                lat=53.0174642,
                lon=-2.5096761,
            ),
            pitch=10,
            zoom=5.3,
        ),
    )

    return fig

In [16]:
fig = create_chart(df)
fig.show(config={'displayModeBar': False})

In [17]:
py.plot(fig, filename="map_test")

'https://chart-studio.plotly.com/~alexhewson/1742/'

### Putting that all together

In [18]:
import chart_studio.plotly as py
import pandas as pd
import plotly.graph_objs as go
import plotly.io as pio

df = pd.DataFrame({"location_name": ["London", "Birmingham", "Manchester", "Cardiff"], "lat": [51.5074, 52.4862, 53.4808, 51.4816], "lon": [-0.1278, -1.8904, -2.2426, -3.1791]})

def generate_traces(df: pd.DataFrame) -> list:
    """Generate traces for the chart."""
    colors = {
        "London": "Blue",
        "Birmingham": "Red",
        "Manchester": "Green",
        "Cardiff": "Yellow",
    }

    traces = [
        go.Scattermap(
            lat = df_location['lat'].tolist(),
            lon = df_location['lon'].tolist(),
            mode = 'markers',
            marker=go.scattermap.Marker(
                size=9,
                color= colors[location],
            ),
            text = df_location['location_name'].tolist(),
            hovertemplate="%{text}",
            name=str(location),
        )
        for location, df_location in df.groupby('location_name')
    ]

    return traces

def create_chart(df: pd.DataFrame) -> go.Figure:

    fig = go.Figure()
    traces = generate_traces(df)
    fig.add_traces(traces)

    fig.update_layout(
        margin=dict(l=0, r=0, t=0, b=0),
        map=dict(
            bearing=0,
            center=dict(
                lat=53.0174642,
                lon=-2.5096761,
            ),
            pitch=10,
            zoom=5.3,
        ),
    )

    return fig

def main() -> go.Figure:
    fig = create_chart(df)
    py.plot(fig, filename="map_test")
    return fig

In [19]:
main()